const $=id=>document.getElementById(id);
const GOOGLE_SCRIPT_URL="https://script.google.com/macros/s/AKfycbwklJqyvIhG_kU6gfba5jPa9ZawJ1HghkaMir9dkHRS8qbZBev2HkAqAj5fIw_l6FWr/exec";
const DEFAULT_EMPLOYEES=["ABDOU TAMBAJAN","CAMARERO 1","CAMARERO 2","CESAR","FELIPE CORDEIRO","LAURA","MAR MORENO","MARTINA COMACHI","MOUSSA SISOKKO","ZAKARIA BANANE"];
let editingId=null,deferredPrompt=null,syncInProgress=false;

function loadEmployees(){try{const s=JSON.parse(localStorage.getItem("veramar_employees")||"[]");return[...new Set([...DEFAULT_EMPLOYEES,...(Array.isArray(s)?s:[])])].sort((a,b)=>a.localeCompare(b,"es"))}catch{return[...DEFAULT_EMPLOYEES]}}
function saveEmployees(v){localStorage.setItem("veramar_employees",JSON.stringify(v))}
function loadRecords(){try{const r=JSON.parse(localStorage.getItem("veramar_records")||"[]");if(!Array.isArray(r))return[];let c=false;const m=r.map(x=>{const y={...x};if(!y.id){y.id=createId();c=true}if(!y.syncStatus){y.syncStatus="pending";c=true}if(!y.operation){y.operation="upsert";c=true}return y});if(c)saveRecords(m);return m}catch{return[]}}
function saveRecords(v){localStorage.setItem("veramar_records",JSON.stringify(v))}
function todayISO(){const d=new Date();return`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`}
function monthKey(d){return String(d||"").slice(0,7)}
function normalizeTime(v){let t=String(v||"").trim().replace(".",":");if(!t)return"";if(/^\d{1,2}$/.test(t))return`${t.padStart(2,"0")}:00`;if(/^\d{3}$/.test(t))return`0${t[0]}:${t.slice(1)}`;if(/^\d{4}$/.test(t))return`${t.slice(0,2)}:${t.slice(2)}`;if(/^\d{1,2}:\d{2}$/.test(t)){const[h,m]=t.split(":").map(Number);if(h>=0&&h<=23&&m>=0&&m<=59)return`${String(h).padStart(2,"0")}:${String(m).padStart(2,"0")}`}return""}
function calcHours(a,b){if(!a||!b)return 0;const[ah,am]=a.split(":").map(Number),[bh,bm]=b.split(":").map(Number);let x=ah*60+am,y=bh*60+bm;if(y<x)y+=1440;return(y-x)/60}
function fmtHours(v){return Number(v||0).toFixed(2).replace(".",",")}
function createId(){return crypto&&crypto.randomUUID?crypto.randomUUID():`${Date.now()}-${Math.random().toString(36).slice(2,12)}`}

function refreshEmployeeSelects(){const e=loadEmployees(),a=$("empleado"),r=$("resumenEmpleado"),cur=r.value;a.innerHTML='<option value="">SELECCIONA EMPLEADO</option>';e.forEach(n=>{const o=document.createElement("option");o.value=n;o.textContent=n;a.appendChild(o)});r.innerHTML="";e.forEach(n=>{const o=document.createElement("option");o.value=n;o.textContent=n;r.appendChild(o)});if(cur&&e.includes(cur))r.value=cur;a.value="";renderEmployeeList()}
function updateHours(){const a=normalizeTime($("entrada").value),b=normalizeTime($("salida").value);$("horas").textContent=fmtHours(calcHours(a,b))}
function showMessage(t,ok=true){$("mensaje").textContent=t;$("mensaje").style.color=ok?"#067647":"#B42318"}
function resetForm(){editingId=null;$("empleado").value="";$("fecha").value=todayISO();$("turno").value="COMIDA";$("entrada").value="";$("salida").value="";$("observaciones").value="";$("horas").textContent="0,00";$("guardarBtn").disabled=false;$("guardarBtn").textContent="Guardar turno"}

function postForm(r,operation="upsert"){const d=new URLSearchParams();["id","empleado","fecha","turno","entrada","salida","horas","observaciones","fechaRegistro"].forEach(k=>d.append(k,r[k]??""));d.append("operation",operation);return fetch(`${GOOGLE_SCRIPT_URL}?t=${Date.now()}`,{method:"POST",mode:"no-cors",cache:"no-store",headers:{"Content-Type":"application/x-www-form-urlencoded;charset=UTF-8"},body:d.toString()})}
function jsonp(params,timeout=12000){return new Promise((resolve,reject)=>{const cb=`veramar_${Date.now()}_${Math.random().toString(36).slice(2)}`,s=document.createElement("script");const timer=setTimeout(()=>{cleanup();reject(new Error("timeout"))},timeout);function cleanup(){clearTimeout(timer);delete window[cb];s.remove()}window[cb]=d=>{cleanup();resolve(d)};const q=new URLSearchParams({...params,callback:cb,t:String(Date.now())});s.src=`${GOOGLE_SCRIPT_URL}?${q}`;s.onerror=()=>{cleanup();reject(new Error("jsonp"))};document.body.appendChild(s)})}
async function verifyRecord(id,exists=true){for(let i=0;i<4;i++){try{const r=await jsonp({action:"exists",id});if(r&&r.ok===true&&r.exists===exists)return true}catch{}await new Promise(res=>setTimeout(res,1200))}return false}
async function syncOne(r){try{const op=r.operation||"upsert";await postForm(r,op);return await verifyRecord(r.id,op!=="delete")}catch{return false}}
async function syncPending(show=false){if(syncInProgress)return;syncInProgress=true;$("sincronizarBtn").disabled=true;const rs=loadRecords();let ok=0,pend=0;for(const r of rs){if(r.syncStatus==="synced")continue;const done=await syncOne(r);r.syncStatus=done?"synced":"pending";done?ok++:pend++;saveRecords(rs);renderSyncStats();renderRecords()}const clean=rs.filter(r=>!(r.operation==="delete"&&r.syncStatus==="synced"));saveRecords(clean);syncInProgress=false;$("sincronizarBtn").disabled=false;renderAll();if(show)showMessage(pend===0?`Sincronización terminada: ${ok} enviados.`:`${ok} enviados y ${pend} pendientes.`,pend===0)}

async function saveTurn(){const empleado=$("empleado").value,fecha=$("fecha").value,turno=$("turno").value,entrada=normalizeTime($("entrada").value),salida=normalizeTime($("salida").value),observaciones=$("observaciones").value.trim();if(!empleado)return showMessage("Selecciona un empleado.",false);if(!fecha)return showMessage("Selecciona la fecha.",false);if(!entrada||!salida)return showMessage("Introduce correctamente entrada y salida.",false);const horas=calcHours(entrada,salida),rs=loadRecords();if(rs.some(r=>r.id!==editingId&&r.operation!=="delete"&&r.empleado===empleado&&r.fecha===fecha&&r.turno===turno&&r.entrada===entrada&&r.salida===salida))return showMessage("Ese turno exacto ya existe.",false);const idx=rs.findIndex(r=>r.id===editingId);const rec={id:editingId||createId(),empleado,fecha,turno,entrada,salida,horas,observaciones,fechaRegistro:idx>=0?rs[idx].fechaRegistro:new Date().toISOString(),syncStatus:"pending",operation:"upsert"};idx>=0?rs[idx]=rec:rs.push(rec);saveRecords(rs);resetForm();renderAll();showMessage(navigator.onLine?"Turno guardado. Sincronizando…":"Turno guardado en el móvil.",true);if(navigator.onLine){await syncPending(false);const u=loadRecords().find(r=>r.id===rec.id);showMessage(u&&u.syncStatus==="synced"?"Turno guardado en Google Sheets.":"Turno guardado en el móvil. Pendiente de sincronizar.",!!(u&&u.syncStatus==="synced"))}}
function editRecord(id){const r=loadRecords().find(x=>x.id===id);if(!r||r.operation==="delete")return;editingId=id;$("empleado").value=r.empleado;$("fecha").value=r.fecha;$("turno").value=r.turno;$("entrada").value=r.entrada;$("salida").value=r.salida;$("observaciones").value=r.observaciones||"";updateHours();$("guardarBtn").textContent="Guardar cambios";scrollTo({top:0,behavior:"smooth"})}
async function deleteRecord(id){if(!confirm("¿Quieres borrar este registro?"))return;const rs=loadRecords(),i=rs.findIndex(r=>r.id===id);if(i<0)return;rs[i].syncStatus==="synced"?rs[i]={...rs[i],operation:"delete",syncStatus:"pending"}:rs.splice(i,1);saveRecords(rs);renderAll();if(navigator.onLine)await syncPending(false)}

function renderRecords(){const l=$("lista");l.innerHTML="";const rs=loadRecords().filter(r=>r.operation!=="delete").sort((a,b)=>(b.fecha+b.entrada).localeCompare(a.fecha+a.entrada)).slice(0,30);if(!rs.length){l.innerHTML="<p>No hay registros todavía.</p>";return}rs.forEach(r=>{const n=$("registroTpl").content.cloneNode(true);n.querySelector(".r-empleado").textContent=r.empleado;n.querySelector(".r-detalle").textContent=`${r.fecha.split("-").reverse().join("/")} · ${r.turno} · ${r.entrada}-${r.salida} · ${fmtHours(r.horas)} h`;const s=n.querySelector(".r-estado");s.textContent=r.syncStatus==="synced"?"Guardado online":"Pendiente de sincronizar";s.className=`r-estado ${r.syncStatus==="synced"?"ok":"pending"}`;n.querySelector(".editar").onclick=()=>editRecord(r.id);n.querySelector(".eliminar").onclick=()=>deleteRecord(r.id);l.appendChild(n)})}
function renderSummary(){const e=$("resumenEmpleado").value,k=monthKey($("fecha").value||todayISO()),rs=loadRecords().filter(r=>r.operation!=="delete"&&r.empleado===e&&monthKey(r.fecha)===k);$("resHoras").textContent=fmtHours(rs.reduce((s,r)=>s+Number(r.horas||0),0));$("resTurnos").textContent=rs.length}
function renderSyncStats(){const rs=loadRecords();$("pendientes").textContent=rs.filter(r=>r.syncStatus!=="synced").length;$("sincronizados").textContent=rs.filter(r=>r.syncStatus==="synced"&&r.operation!=="delete").length}
function updateOnlineBadge(){const b=$("onlineBadge");b.textContent=navigator.onLine?"Con conexión":"Sin conexión";b.className=`badge ${navigator.onLine?"online":"offline"}`}
function exportCSV(){const rs=loadRecords().filter(r=>r.operation!=="delete").sort((a,b)=>a.fecha.localeCompare(b.fecha)),h=["ID","EMPLEADO","FECHA","TURNO","ENTRADA","SALIDA","HORAS","OBSERVACIONES","FECHA_REGISTRO","ESTADO"];const csv=[h,...rs.map(r=>[r.id,r.empleado,r.fecha,r.turno,r.entrada,r.salida,String(r.horas).replace(".",","),r.observaciones||"",r.fechaRegistro,r.syncStatus])].map(row=>row.map(v=>`"${String(v).replaceAll('"','""')}"`).join(";")).join("\n");const blob=new Blob(["\uFEFF"+csv],{type:"text/csv;charset=utf-8"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=`veramar_turnos_${todayISO()}.csv`;a.click();URL.revokeObjectURL(a.href)}
function renderEmployeeList(){const c=$("empleadosLista");c.innerHTML="";loadEmployees().forEach(n=>{const r=document.createElement("div");r.className="employee-item";const s=document.createElement("span");s.textContent=n;const b=document.createElement("button");b.className="danger small";b.textContent="Quitar";b.onclick=()=>{if(confirm(`¿Quieres quitar a ${n}?`)){saveEmployees(loadEmployees().filter(x=>x!==n));refreshEmployeeSelects();renderAll()}};r.append(s,b);c.appendChild(r)})}
function addEmployee(){const n=$("nuevoEmpleado").value.trim().toUpperCase();if(!n)return;const e=loadEmployees();if(!e.includes(n)){e.push(n);saveEmployees(e)}$("nuevoEmpleado").value="";refreshEmployeeSelects();renderAll()}
function renderAll(){renderRecords();renderSummary();renderSyncStats();updateOnlineBadge()}

$("guardarBtn").onclick=saveTurn;$("exportarBtn").onclick=exportCSV;$("sincronizarBtn").onclick=()=>syncPending(true);$("anadirEmpleadoBtn").onclick=addEmployee;
$("entrada").addEventListener("blur",()=>{const t=normalizeTime($("entrada").value);if(t)$("entrada").value=t;updateHours()});
$("salida").addEventListener("blur",()=>{const t=normalizeTime($("salida").value);if(t)$("salida").value=t;updateHours()});
$("resumenEmpleado").onchange=renderSummary;$("fecha").onchange=renderSummary;
addEventListener("online",()=>{updateOnlineBadge();syncPending(false)});addEventListener("offline",updateOnlineBadge);
addEventListener("beforeinstallprompt",e=>{e.preventDefault();deferredPrompt=e;$("installBtn").classList.remove("hidden")});
$("installBtn").onclick=async()=>{if(!deferredPrompt)return;deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;$("installBtn").classList.add("hidden")};
if("serviceWorker"in navigator)navigator.serviceWorker.register("sw.js");
refreshEmployeeSelects();resetForm();renderAll();if(navigator.onLine)setTimeout(()=>syncPending(false),700);
